version: "3"
    
services:
  pullbaseddb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noc@1235
      MYSQL_DATABASE: provisioning_store_test
      MYSQL_USER: test
      MYSQL_PASSWORD: noc@1235
  pullbased:
    depends_on:
       - pullbaseddb
    image: tests_pullbased
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ./app:/code
    working_dir: /code
    command: bash tests/start.sh
  sbox:
    image: tests_pullbased
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ./app/tests/server/:/code
    working_dir: /code
    command: python3 server.py
