version: '3'

services:
  pullbased:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    image: pullbased:staging
    command: ["pytest"]
    networks:
      - dockersubnet
    environment:
      - NODE_ENV=docker

networks:
  default:
    external:
      name: dockersubnet