#! /bin/bash
# CONTACT ashish.sharma@sugarboxnetworks.com to discuss any changes to build pipeline
# DO NOT EDIT THIS FILE !

# Wait for the database to start up pending the environment.
if [ $NODE_ENV = 'docker' ]; then
    bash /wait-for-it.sh pullbaseddb:3306 -t 120
fi

# Run the supplied application
exec "$@"